package kr.ac.kopo.ocr.controller;

import org.springframework.beans.factory.support.ReplaceOverride;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

@Controller
public class OcrController {
	
	
	@RequestMapping("/ocr")
	public ModelAndView generalOcr() {
		
		
		OkHttpClient client = new OkHttpClient();
		
		
		ModelAndView mav = new ModelAndView("ocr/generalOcr"); 
		
		MediaType mediaType = MediaType.parse("application/json");
		
		RequestBody body = RequestBody.create(mediaType, "{\n\t\"version\" : \"V1\","
				+ "\n\t\"requestId\" : \"test2\","
				+ "\n\t\"timestamp\" : 0,"
				+ "\n\t\"images\" :[{\n\t\t\n\t\t\"format\" : \"png\","
				+ "\n\t\t\"url\" : \"https://kr.object.ncloudstorage.com/testbucke/KakaoTalk_20210815_174210497.png\","
				+ "\n\t\t\"name\" : \"KakaoTalk_20210815_174210497.png\"\n\t}]\n}");
		
		Request request = new Request.Builder()
				.url("https://55c7547061ee4d91891f615ee5e7c101.apigw.ntruss.com/custom/v1/10737/a4ea6ab1e2b24fda85a939e66443d9c380440ecaf6e6e6069e248761c5a0353b/general")
				.post(body)
				.addHeader("content-type", "application/json")
				.addHeader("x-ocr-secret", "cHBIclVDQnZaV3NkQVJBUnRhaGdsaGxMTEllSEtzSkM=")
				.addHeader("cache-control", "no-cache")
//		  		.addHeader("postman-token", "31917011-c262-8273-4761-7a87eef0d3fa")
				.build();
		
		try {
			
			Response response = client.newCall(request).execute();
			ResponseBody responseBody = response.body();
			
			// general OCR로 받아온 결과값 출력
			
			String result = responseBody.string();
			System.out.println("api로 받아온 general OCR : " + result);
			
			
			
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return mav;
		
	}
	
	
	@RequestMapping("/ocr/test")
	@org.springframework.web.bind.annotation.ResponseBody
	public String testOcr() {
		

		// 숫자와 공백을 제외하고 정규식으로 공백으로 치환해보자
		// 원본은 그대로 유지되고, 바뀐 문자열이 새로 생성이 되어서 반환됨, 그래서 항상 바뀐 문자열을 반환값으로 받아야함
		
		String result = "{\r\n"
				+ "    \"version\": \"V1\",\r\n"
				+ "    \"requestId\": \"test2\",\r\n"
				+ "    \"timestamp\": 1629883282112,\r\n"
				+ "    \"images\": [\r\n"
				+ "        {\r\n"
				+ "            \"uid\": \"08808004194f4a88af5d992dbd041ae6\",\r\n"
				+ "            \"name\": \"test3\",\r\n"
				+ "            \"inferResult\": \"SUCCESS\",\r\n"
				+ "            \"message\": \"SUCCESS\",\r\n"
				+ "            \"validationResult\": {\r\n"
				+ "                \"result\": \"NO_REQUESTED\"\r\n"
				+ "            },\r\n"
				+ "            \"fields\": [\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 907,\r\n"
				+ "                                \"y\": 357\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1075,\r\n"
				+ "                                \"y\": 367\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1070,\r\n"
				+ "                                \"y\": 455\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 902,\r\n"
				+ "                                \"y\": 445\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"No\",\r\n"
				+ "                    \"inferConfidence\": 0.9996\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1086,\r\n"
				+ "                                \"y\": 356\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1432,\r\n"
				+ "                                \"y\": 356\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1432,\r\n"
				+ "                                \"y\": 446\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1086,\r\n"
				+ "                                \"y\": 446\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"Brand\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1556,\r\n"
				+ "                                \"y\": 392\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1956,\r\n"
				+ "                                \"y\": 404\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1953,\r\n"
				+ "                                \"y\": 508\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1553,\r\n"
				+ "                                \"y\": 497\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"Burger\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 849,\r\n"
				+ "                                \"y\": 598\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1352,\r\n"
				+ "                                \"y\": 598\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1352,\r\n"
				+ "                                \"y\": 702\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 849,\r\n"
				+ "                                \"y\": 702\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[판매영수증]\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 811,\r\n"
				+ "                                \"y\": 806\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1503,\r\n"
				+ "                                \"y\": 806\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1503,\r\n"
				+ "                                \"y\": 1001\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 811,\r\n"
				+ "                                \"y\": 1001\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"주문번호\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1565,\r\n"
				+ "                                \"y\": 849\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1641,\r\n"
				+ "                                \"y\": 849\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1641,\r\n"
				+ "                                \"y\": 963\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1565,\r\n"
				+ "                                \"y\": 963\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \":\",\r\n"
				+ "                    \"inferConfidence\": 0.9996\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1707,\r\n"
				+ "                                \"y\": 802\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2082,\r\n"
				+ "                                \"y\": 802\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2082,\r\n"
				+ "                                \"y\": 987\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1707,\r\n"
				+ "                                \"y\": 987\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"5106\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 564,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 711,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 711,\r\n"
				+ "                                \"y\": 1162\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 564,\r\n"
				+ "                                \"y\": 1162\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"NBB\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 740,\r\n"
				+ "                                \"y\": 1069\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1367,\r\n"
				+ "                                \"y\": 1075\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1366,\r\n"
				+ "                                \"y\": 1183\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 739,\r\n"
				+ "                                \"y\": 1176\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"인천용현점/인천\",\r\n"
				+ "                    \"inferConfidence\": 0.9963\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1394,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1741,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1741,\r\n"
				+ "                                \"y\": 1186\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1394,\r\n"
				+ "                                \"y\": 1186\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"미추홀구\",\r\n"
				+ "                    \"inferConfidence\": 0.9996\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1764,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2025,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2025,\r\n"
				+ "                                \"y\": 1176\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1764,\r\n"
				+ "                                \"y\": 1176\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"인하로\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2051,\r\n"
				+ "                                \"y\": 1072\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2233,\r\n"
				+ "                                \"y\": 1065\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2237,\r\n"
				+ "                                \"y\": 1157\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2054,\r\n"
				+ "                                \"y\": 1164\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"81-1\",\r\n"
				+ "                    \"inferConfidence\": 0.9996\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 1176\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 754,\r\n"
				+ "                                \"y\": 1176\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 754,\r\n"
				+ "                                \"y\": 1276\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 1276\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"대표\",\r\n"
				+ "                    \"inferConfidence\": 0.9996\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 783,\r\n"
				+ "                                \"y\": 1205\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 825,\r\n"
				+ "                                \"y\": 1205\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 825,\r\n"
				+ "                                \"y\": 1266\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 783,\r\n"
				+ "                                \"y\": 1266\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \":\",\r\n"
				+ "                    \"inferConfidence\": 0.9994\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 863,\r\n"
				+ "                                \"y\": 1190\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1698,\r\n"
				+ "                                \"y\": 1190\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1698,\r\n"
				+ "                                \"y\": 1285\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 863,\r\n"
				+ "                                \"y\": 1285\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"이경미 (289-43-00764)\",\r\n"
				+ "                    \"inferConfidence\": 0.9183\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 1295\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 702,\r\n"
				+ "                                \"y\": 1295\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 702,\r\n"
				+ "                                \"y\": 1366\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 1366\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"T:\",\r\n"
				+ "                    \"inferConfidence\": 0.9629\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 731,\r\n"
				+ "                                \"y\": 1294\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1253,\r\n"
				+ "                                \"y\": 1300\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1252,\r\n"
				+ "                                \"y\": 1396\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 729,\r\n"
				+ "                                \"y\": 1389\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"032-873-0508\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 560,\r\n"
				+ "                                \"y\": 1502\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1012,\r\n"
				+ "                                \"y\": 1515\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1010,\r\n"
				+ "                                \"y\": 1611\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 558,\r\n"
				+ "                                \"y\": 1598\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"2021-08-14\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1029,\r\n"
				+ "                                \"y\": 1518\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1157,\r\n"
				+ "                                \"y\": 1518\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1157,\r\n"
				+ "                                \"y\": 1608\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1029,\r\n"
				+ "                                \"y\": 1608\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"10:\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1153,\r\n"
				+ "                                \"y\": 1518\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1276,\r\n"
				+ "                                \"y\": 1518\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1276,\r\n"
				+ "                                \"y\": 1603\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1153,\r\n"
				+ "                                \"y\": 1603\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"56:\",\r\n"
				+ "                    \"inferConfidence\": 0.999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1276,\r\n"
				+ "                                \"y\": 1518\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1380,\r\n"
				+ "                                \"y\": 1518\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1380,\r\n"
				+ "                                \"y\": 1608\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1276,\r\n"
				+ "                                \"y\": 1608\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"44\",\r\n"
				+ "                    \"inferConfidence\": 0.9998\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1760,\r\n"
				+ "                                \"y\": 1513\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1935,\r\n"
				+ "                                \"y\": 1513\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1935,\r\n"
				+ "                                \"y\": 1603\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1760,\r\n"
				+ "                                \"y\": 1603\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"POS:\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1930,\r\n"
				+ "                                \"y\": 1513\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2025,\r\n"
				+ "                                \"y\": 1513\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2025,\r\n"
				+ "                                \"y\": 1598\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1930,\r\n"
				+ "                                \"y\": 1598\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"51\",\r\n"
				+ "                    \"inferConfidence\": 0.9998\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2016,\r\n"
				+ "                                \"y\": 1499\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2324,\r\n"
				+ "                                \"y\": 1499\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2324,\r\n"
				+ "                                \"y\": 1598\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2016,\r\n"
				+ "                                \"y\": 1598\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"(00006)\",\r\n"
				+ "                    \"inferConfidence\": 0.9991\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 566,\r\n"
				+ "                                \"y\": 1712\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 837,\r\n"
				+ "                                \"y\": 1720\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 834,\r\n"
				+ "                                \"y\": 1833\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 562,\r\n"
				+ "                                \"y\": 1825\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"상품명\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1679,\r\n"
				+ "                                \"y\": 1722\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1864,\r\n"
				+ "                                \"y\": 1722\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1864,\r\n"
				+ "                                \"y\": 1835\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1679,\r\n"
				+ "                                \"y\": 1835\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"수량\",\r\n"
				+ "                    \"inferConfidence\": 0.9995\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2139,\r\n"
				+ "                                \"y\": 1712\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2324,\r\n"
				+ "                                \"y\": 1712\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2324,\r\n"
				+ "                                \"y\": 1821\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2139,\r\n"
				+ "                                \"y\": 1821\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"금액\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 1945\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 631,\r\n"
				+ "                                \"y\": 1945\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 631,\r\n"
				+ "                                \"y\": 2025\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 2025\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"T\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 650,\r\n"
				+ "                                \"y\": 1945\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 802,\r\n"
				+ "                                \"y\": 1945\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 802,\r\n"
				+ "                                \"y\": 2035\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 650,\r\n"
				+ "                                \"y\": 2035\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"NBB\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 821,\r\n"
				+ "                                \"y\": 1940\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1162,\r\n"
				+ "                                \"y\": 1940\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1162,\r\n"
				+ "                                \"y\": 2044\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 821,\r\n"
				+ "                                \"y\": 2044\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"시그니처\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1817,\r\n"
				+ "                                \"y\": 2058\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1859,\r\n"
				+ "                                \"y\": 2058\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1859,\r\n"
				+ "                                \"y\": 2139\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1817,\r\n"
				+ "                                \"y\": 2139\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"1\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 2049\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2333,\r\n"
				+ "                                \"y\": 2049\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2333,\r\n"
				+ "                                \"y\": 2144\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 2144\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,500\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 2267\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 669,\r\n"
				+ "                                \"y\": 2267\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 669,\r\n"
				+ "                                \"y\": 2352\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 569,\r\n"
				+ "                                \"y\": 2352\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"소\",\r\n"
				+ "                    \"inferConfidence\": 0.9995\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 863,\r\n"
				+ "                                \"y\": 2262\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 958,\r\n"
				+ "                                \"y\": 2262\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 958,\r\n"
				+ "                                \"y\": 2362\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 863,\r\n"
				+ "                                \"y\": 2362\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"계\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1812,\r\n"
				+ "                                \"y\": 2267\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1864,\r\n"
				+ "                                \"y\": 2267\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1864,\r\n"
				+ "                                \"y\": 2352\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1812,\r\n"
				+ "                                \"y\": 2352\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"1\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 2262\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2333,\r\n"
				+ "                                \"y\": 2262\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2333,\r\n"
				+ "                                \"y\": 2357\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 2357\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,500\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1518,\r\n"
				+ "                                \"y\": 2476\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1859,\r\n"
				+ "                                \"y\": 2476\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1859,\r\n"
				+ "                                \"y\": 2580\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1518,\r\n"
				+ "                                \"y\": 2580\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"과세금액\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 2481\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2333,\r\n"
				+ "                                \"y\": 2481\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2333,\r\n"
				+ "                                \"y\": 2575\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 2575\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,182\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1522,\r\n"
				+ "                                \"y\": 2585\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1864,\r\n"
				+ "                                \"y\": 2585\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1864,\r\n"
				+ "                                \"y\": 2694\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1522,\r\n"
				+ "                                \"y\": 2694\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"부가세\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2182,\r\n"
				+ "                                \"y\": 2590\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2338,\r\n"
				+ "                                \"y\": 2590\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2338,\r\n"
				+ "                                \"y\": 2684\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2182,\r\n"
				+ "                                \"y\": 2684\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"318\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 564,\r\n"
				+ "                                \"y\": 2803\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 915,\r\n"
				+ "                                \"y\": 2803\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 915,\r\n"
				+ "                                \"y\": 2912\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 564,\r\n"
				+ "                                \"y\": 2912\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"총매출액\",\r\n"
				+ "                    \"inferConfidence\": 0.9994\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2101,\r\n"
				+ "                                \"y\": 2813\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2338,\r\n"
				+ "                                \"y\": 2813\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2338,\r\n"
				+ "                                \"y\": 2907\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2101,\r\n"
				+ "                                \"y\": 2907\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,500\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 564,\r\n"
				+ "                                \"y\": 2912\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 915,\r\n"
				+ "                                \"y\": 2912\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 915,\r\n"
				+ "                                \"y\": 3021\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 564,\r\n"
				+ "                                \"y\": 3021\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"할인금액\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2267,\r\n"
				+ "                                \"y\": 2917\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2348,\r\n"
				+ "                                \"y\": 2917\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2348,\r\n"
				+ "                                \"y\": 3021\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2267,\r\n"
				+ "                                \"y\": 3021\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"0\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 558,\r\n"
				+ "                                \"y\": 3023\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 915,\r\n"
				+ "                                \"y\": 3016\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 917,\r\n"
				+ "                                \"y\": 3130\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 560,\r\n"
				+ "                                \"y\": 3136\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"합계금액\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 3026\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2343,\r\n"
				+ "                                \"y\": 3026\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2343,\r\n"
				+ "                                \"y\": 3130\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2096,\r\n"
				+ "                                \"y\": 3130\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,500\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 560,\r\n"
				+ "                                \"y\": 3258\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 621,\r\n"
				+ "                                \"y\": 3258\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 621,\r\n"
				+ "                                \"y\": 3344\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 560,\r\n"
				+ "                                \"y\": 3344\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 642,\r\n"
				+ "                                \"y\": 3244\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1005,\r\n"
				+ "                                \"y\": 3235\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1008,\r\n"
				+ "                                \"y\": 3347\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 646,\r\n"
				+ "                                \"y\": 3357\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"신용카드\",\r\n"
				+ "                    \"inferConfidence\": 0.9998\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1020,\r\n"
				+ "                                \"y\": 3244\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1091,\r\n"
				+ "                                \"y\": 3244\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1091,\r\n"
				+ "                                \"y\": 3339\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1020,\r\n"
				+ "                                \"y\": 3339\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"]\",\r\n"
				+ "                    \"inferConfidence\": 0.9993\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2106,\r\n"
				+ "                                \"y\": 3254\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2352,\r\n"
				+ "                                \"y\": 3254\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2352,\r\n"
				+ "                                \"y\": 3353\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2106,\r\n"
				+ "                                \"y\": 3353\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,500\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1186,\r\n"
				+ "                                \"y\": 3458\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1703,\r\n"
				+ "                                \"y\": 3458\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1703,\r\n"
				+ "                                \"y\": 3567\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1186,\r\n"
				+ "                                \"y\": 3567\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[비씨카드사]\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 552,\r\n"
				+ "                                \"y\": 3585\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 995,\r\n"
				+ "                                \"y\": 3572\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 998,\r\n"
				+ "                                \"y\": 3680\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 555,\r\n"
				+ "                                \"y\": 3693\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[결제금액]\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2106,\r\n"
				+ "                                \"y\": 3590\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2352,\r\n"
				+ "                                \"y\": 3590\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2352,\r\n"
				+ "                                \"y\": 3695\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2106,\r\n"
				+ "                                \"y\": 3695\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"3,500\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 550,\r\n"
				+ "                                \"y\": 3695\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 3695\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 3799\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 550,\r\n"
				+ "                                \"y\": 3799\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[카드번호]\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1651,\r\n"
				+ "                                \"y\": 3699\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2344,\r\n"
				+ "                                \"y\": 3714\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2342,\r\n"
				+ "                                \"y\": 3803\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1649,\r\n"
				+ "                                \"y\": 3787\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"946044**********\",\r\n"
				+ "                    \"inferConfidence\": 0.9998\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 545,\r\n"
				+ "                                \"y\": 3809\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 3809\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 3913\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 545,\r\n"
				+ "                                \"y\": 3913\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[가맹번호]\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1940,\r\n"
				+ "                                \"y\": 3809\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2350,\r\n"
				+ "                                \"y\": 3820\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2347,\r\n"
				+ "                                \"y\": 3923\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1938,\r\n"
				+ "                                \"y\": 3912\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"724040201\",\r\n"
				+ "                    \"inferConfidence\": 0.9998\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 545,\r\n"
				+ "                                \"y\": 3922\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 3922\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 4031\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 545,\r\n"
				+ "                                \"y\": 4031\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[승인번호]\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1646,\r\n"
				+ "                                \"y\": 3916\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2354,\r\n"
				+ "                                \"y\": 3929\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2352,\r\n"
				+ "                                \"y\": 4043\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1644,\r\n"
				+ "                                \"y\": 4031\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"75678191[일시불]\",\r\n"
				+ "                    \"inferConfidence\": 0.9675\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 544,\r\n"
				+ "                                \"y\": 4037\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 991,\r\n"
				+ "                                \"y\": 4031\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 992,\r\n"
				+ "                                \"y\": 4139\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 546,\r\n"
				+ "                                \"y\": 4146\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"[거래일시]\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1522,\r\n"
				+ "                                \"y\": 4036\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1978,\r\n"
				+ "                                \"y\": 4036\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1978,\r\n"
				+ "                                \"y\": 4136\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1522,\r\n"
				+ "                                \"y\": 4136\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"2021-08-14\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1997,\r\n"
				+ "                                \"y\": 4046\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2130,\r\n"
				+ "                                \"y\": 4046\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2130,\r\n"
				+ "                                \"y\": 4141\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1997,\r\n"
				+ "                                \"y\": 4141\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"10:\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2125,\r\n"
				+ "                                \"y\": 4050\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2258,\r\n"
				+ "                                \"y\": 4050\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2258,\r\n"
				+ "                                \"y\": 4145\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2125,\r\n"
				+ "                                \"y\": 4145\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"56:\",\r\n"
				+ "                    \"inferConfidence\": 0.9995\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2248,\r\n"
				+ "                                \"y\": 4050\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2362,\r\n"
				+ "                                \"y\": 4050\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2362,\r\n"
				+ "                                \"y\": 4150\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2248,\r\n"
				+ "                                \"y\": 4150\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"36\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 541,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 735,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 735,\r\n"
				+ "                                \"y\": 4359\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 541,\r\n"
				+ "                                \"y\": 4359\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"WIFI\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 764,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 868,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 868,\r\n"
				+ "                                \"y\": 4354\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 764,\r\n"
				+ "                                \"y\": 4354\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"ID\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 896,\r\n"
				+ "                                \"y\": 4288\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 939,\r\n"
				+ "                                \"y\": 4288\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 939,\r\n"
				+ "                                \"y\": 4344\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 896,\r\n"
				+ "                                \"y\": 4344\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \":\",\r\n"
				+ "                    \"inferConfidence\": 0.9997\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 968,\r\n"
				+ "                                \"y\": 4264\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1333,\r\n"
				+ "                                \"y\": 4264\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1333,\r\n"
				+ "                                \"y\": 4354\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 968,\r\n"
				+ "                                \"y\": 4354\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"NBB_WIFI\",\r\n"
				+ "                    \"inferConfidence\": 0.9993\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1356,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1418,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1418,\r\n"
				+ "                                \"y\": 4349\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1356,\r\n"
				+ "                                \"y\": 4349\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"/\",\r\n"
				+ "                    \"inferConfidence\": 1\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1437,\r\n"
				+ "                                \"y\": 4264\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1551,\r\n"
				+ "                                \"y\": 4264\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1551,\r\n"
				+ "                                \"y\": 4354\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1437,\r\n"
				+ "                                \"y\": 4354\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"PW\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1575,\r\n"
				+ "                                \"y\": 4288\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1617,\r\n"
				+ "                                \"y\": 4288\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1617,\r\n"
				+ "                                \"y\": 4344\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1575,\r\n"
				+ "                                \"y\": 4344\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \":\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1646,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2006,\r\n"
				+ "                                \"y\": 4269\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 2006,\r\n"
				+ "                                \"y\": 4363\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1646,\r\n"
				+ "                                \"y\": 4363\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"NBB1234!\",\r\n"
				+ "                    \"inferConfidence\": 0.9996\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 545,\r\n"
				+ "                                \"y\": 4378\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 640,\r\n"
				+ "                                \"y\": 4378\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 640,\r\n"
				+ "                                \"y\": 4482\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 545,\r\n"
				+ "                                \"y\": 4482\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"이\",\r\n"
				+ "                    \"inferConfidence\": 0.9998\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 678,\r\n"
				+ "                                \"y\": 4368\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1034,\r\n"
				+ "                                \"y\": 4368\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1034,\r\n"
				+ "                                \"y\": 4482\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 678,\r\n"
				+ "                                \"y\": 4482\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"영수증은\",\r\n"
				+ "                    \"inferConfidence\": 0.9999\r\n"
				+ "                },\r\n"
				+ "                {\r\n"
				+ "                    \"valueType\": \"ALL\",\r\n"
				+ "                    \"boundingPoly\": {\r\n"
				+ "                        \"vertices\": [\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1058,\r\n"
				+ "                                \"y\": 4368\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1541,\r\n"
				+ "                                \"y\": 4368\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1541,\r\n"
				+ "                                \"y\": 4482\r\n"
				+ "                            },\r\n"
				+ "                            {\r\n"
				+ "                                \"x\": 1058,\r\n"
				+ "                                \"y\": 4482\r\n"
				+ "                            }\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    \"inferText\": \"교환/환불시\",\r\n"
				+ "                    \"inferConf";
		
		
		
		
		
		return result;
		
	}
	
	
}
		
		
		
		
		

	
	


